apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: pi-k8s-test
  namespace: ingress-nginx
spec:
  replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: pi-k8s-test
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: pi-k8s-test
    spec:
      # 定义容器，可以多个
      containers:
      - name: pi-k8s-test # 容器名字
        image: zhaoolee/pi-k8s-test:001 # 镜像

---
apiVersion: v1
kind: Service
metadata:
  name: pi-k8s-test
spec:
  selector:
    app: pi-k8s-test
  type: ClusterIP
  ports:
    - port: 3000        # 本 Service 的端口
      targetPort: 3000  # 容器端口