apiVersion: apps/v1
kind: Deployment
metadata:
  # 部署名字
  name: k8s-test-hexo
  namespace: ingress-nginx
spec:
  replicas: 2
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: k8s-test-hexo
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: k8s-test-hexo
    spec:
      # 定义容器，可以多个
      containers:
      - name: k8s-test-hexo # 容器名字
        image: taskbjorn/hexo:5.2.0 # 镜像

---
apiVersion: v1
kind: Service
metadata:
  name: k8s-test-hexo
spec:
  selector:
    app: k8s-test-hexo
  type: ClusterIP
  ports:
    - port: 4000        # 本 Service 的端口
      targetPort: 4000  # 容器端口